#!/bin/bash

clear

echo "______________________________________________"
echo "|  ™POMBO                                    |\ "
echo "|   _____________________________________    | \ "
echo "|   |   _______________|________   |  - ×|   |  \ "
echo "|   |   |•___________________- ×|  |     |   |   \ "
echo "|   |   |                       |  |     |   |    |"
echo "|   |   | 1 INICIAR ACCLAN      |  |     |   |    |"
echo "|   |   |                       |__|     |   |\   |"
echo "|   |   | 2 DESISTALAR ACCLAN   ||       |   | \  |"
echo "|   |   |                       ||       |   |  \ |"
echo "|   |   | 3 REINSTALAR ACCLAN   ||       |   |   \|"
echo "|   |   |_______________________||       |   |    |"
echo "|   |     '----------------------'       |   |    |"
echo "|   |                    0 -  DESLIGAR   |   |    |"
echo "|   |____________________________________|   |    |"
echo "|   |____________________________°_°_°___|   |    |"
echo "|                                            |    |"
echo "=================================================="

read opcao

if [ $opcao = 0 ] || [ $opcao = 1 ] || [ $opcao = 2 ] || [ $opcao = 3 ]

then

&>/dev/null

else

./fex

fi

if [ $opcao = 1 ]
then

clear 

echo "______________________________________________"
echo "|                                            |\ "
echo "|   _____________________________________    | \ "
echo "|   |   _______________|________   |  - ×|   |  \ "
echo "|   |   |•___________________- ×|  |     |   |   \ "
echo "|   |   |                       |  |     |   |    |"
echo "|   |   | CARRENGANDO ACCLAN..  |  |     |   |    |"
echo "|   |   |                       |__|     |   |\   |"
echo "|   |   |                       ||       |   | \  |"
echo "|   |   |                       ||       |   |  \ |"
echo "|   |   |                    :) ||       |   |   \|"
echo "|   |   |_______________________||       |   |    |"
echo "|   |     '----------------------'       |   |    |"
echo "|   |                            ™POMBO  |   |    |"
echo "|   |____________________________________|   |    |"
echo "|   |____________________________°_°_°___|   |    |"
echo "|                                            |    |"
echo "=================================================="

    if [ -d /data/data/com.termux/files/home/ACCLAN ]
    then

        clear

        unset LD_PRELOAD

        export PATH=/sbin:/usr/bin:/usr/sbin:/system/bin:/system/xbin:$PATH

        export USER=root

        export HOME=/root

        export LANGUAGE=C

        export LANG=C

        folder=/data/data/com.termux/files/home/ACCLAN

        echo -e "\x1b[33m [ Mounting system folders ]"

clear

echo "______________________________________________"
echo "|                                            |\ "
echo "|   _____________________________________    | \ "
echo "|   |   _______________|________   |  - ×|   |  \ "
echo "|   |   |•___________________- ×|  |     |   |   \ "
echo "|   |   |                       |  |     |   |    |"
echo "|   |   | MONTANDO / DEV...     |  |     |   |    |"
echo "|   |   |                       |__|     |   |\   |"
echo "|   |   |                       ||       |   | \  |"
echo "|   |   |                       ||       |   |  \ |"
echo "|   |   |                    :) ||       |   |   \|"
echo "|   |   |_______________________||       |   |    |"
echo "|   |     '----------------------'       |   |    |"
echo "|   |                            ™POMBO  |   |    |"
echo "|   |____________________________________|   |    |"
echo "|   |____________________________°_°_°___|   |    |"
echo "|                                            |    |"
echo "=================================================="

        sudo mount --bind /dev $folder/dev

clear

echo "______________________________________________"
echo "|                                            |\ "
echo "|   _____________________________________    | \ "
echo "|   |   _______________|________   |  - ×|   |  \ "
echo "|   |   |•___________________- ×|  |     |   |   \ "
echo "|   |   |                       |  |     |   |    |"
echo "|   |   | MONTANDO / DEV...     |  |     |   |    |"
echo "|   |   |                       |__|     |   |\   |"
echo "|   |   | MONTANDO / SYS...     ||       |   | \  |"
echo "|   |   |                       ||       |   |  \ |"
echo "|   |   |                    :) ||       |   |   \|"
echo "|   |   |_______________________||       |   |    |"
echo "|   |     '----------------------'       |   |    |"
echo "|   |                            ™POMBO  |   |    |"
echo "|   |____________________________________|   |    |"
echo "|   |____________________________°_°_°___|   |    |"
echo "|                                            |    |"
echo "=================================================="

        sudo mount --bind /sys $folder/sys

clear

echo "______________________________________________"
echo "|                                            |\ "
echo "|   _____________________________________    | \ "
echo "|   |   _______________|________   |  - ×|   |  \ "
echo "|   |   |•___________________- ×|  |     |   |   \ "
echo "|   |   |                       |  |     |   |    |"
echo "|   |   | MONTANDO / DEV...     |  |     |   |    |"
echo "|   |   |                       |__|     |   |\   |"
echo "|   |   | MONTANDO / SYS...     ||       |   | \  |"
echo "|   |   |                       ||       |   |  \ |"
echo "|   |   | MONTANDO / PROC    :) ||       |   |   \|"
echo "|   |   |_______________________||       |   |    |"
echo "|   |     '----------------------'       |   |    |"
echo "|   |                            ™POMBO  |   |    |"
echo "|   |____________________________________|   |    |"
echo "|   |____________________________°_°_°___|   |    |"
echo "|                                            |    |"
echo "=================================================="

        sudo mount --bind /proc $folder/proc

clear

echo "______________________________________________"
echo "|                                            |\ "
echo "|   _____________________________________    | \ "
echo "|   |   _______________|________   |  - ×|   |  \ "
echo "|   |   |•___________________- ×|  |     |   |   \ "
echo "|   |   |                       |  |     |   |    |"
echo "|   |   | MONTANDO / SYS...     |  |     |   |    |"
echo "|   |   |                       |__|     |   |\   |"
echo "|   |   | MONTANDO / PROC..     ||       |   | \  |"
echo "|   |   |                       ||       |   |  \ |"
echo "|   |   | MONTANDO / PTS     :) ||       |   |   \|"
echo "|   |   |_______________________||       |   |    |"
echo "|   |     '----------------------'       |   |    |"
echo "|   |                            ™POMBO  |   |    |"
echo "|   |____________________________________|   |    |"
echo "|   |____________________________°_°_°___|   |    |"
echo "|                                            |    |"
echo "=================================================="

        sudo mount --bind /dev/pts $folder/dev/pts

clear

echo "______________________________________________"
echo "|                                            |\ "
echo "|   _____________________________________    | \ "
echo "|   |   _______________|________   |  - ×|   |  \ "
echo "|   |   |•___________________- ×|  |     |   |   \ "
echo "|   |   |                       |  |     |   |    |"
echo "|   |   | MONTANDO / PROC...    |  |     |   |    |"
echo "|   |   |                       |__|     |   |\   |"
echo "|   |   | MONTANDO / PTS...     ||       |   | \  |"
echo "|   |   |                       ||       |   |  \ |"
echo "|   |   | MONTANDO / SDCARD  :) ||       |   |   \|"
echo "|   |   |_______________________||       |   |    |"
echo "|   |     '----------------------'       |   |    |"
echo "|   |                            ™POMBO  |   |    |"
echo "|   |____________________________________|   |    |"
echo "|   |____________________________°_°_°___|   |    |"
echo "|                                            |    |"
echo "=================================================="

         sudo mount --bind /sdcard $folder/sdcard

clear

echo "______________________________________________"
echo "|                                            |\ "
echo "|   _____________________________________    | \ "
echo "|   |   _______________|________   |  - ×|   |  \ "
echo "|   |   |•___________________- ×|  |     |   |   \ "
echo "|   |   |                       |  |     |   |    |"
echo "|   |   | MONTANDO / PTS...     |  |     |   |    |"
echo "|   |   |                       |__|     |   |\   |"
echo "|   |   | MONTANDO / SDCARD...  ||       |   | \  |"
echo "|   |   |                       ||       |   |  \ |"
echo "|   |   | ROOTFS MONTADO     :) ||       |   |   \|"
echo "|   |   |_______________________||       |   |    |"
echo "|   |     '----------------------'       |   |    |"
echo "|   |                            ™POMBO  |   |    |"
echo "|   |____________________________________|   |    |"
echo "|   |____________________________°_°_°___|   |    |"
echo "|                                            |    |"
echo "=================================================="

       sudo touch /data/data/com.termux/files/home/Fex/opt/chroot
       
       termux-x11 :0 &>/dev/null & pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 &>/dev/null & sleep 1
	
       sudo mount --bind $PREFIX/tmp/ $folder/tmp/
	
       
clear

echo "______________________________________________"
echo "|                                            |\ "
echo "|   _____________________________________    | \ "
echo "|   |   _______________|________   |  - ×|   |  \ "
echo "|   |   |•___________________- ×|  |     |   |   \ "
echo "|   |   |                       |  |     |   |    |"
echo "|   |   | MONTANDO / SDCARD     |  |     |   |    |"
echo "|   |   |                       |__|     |   |\   |"
echo "|   |   | ROOTFS MONTADO        ||       |   | \  |"
echo "|   |   |                       ||       |   |  \ |"
echo "|   |   | INICIANDO          :) ||       |   |   \|"
echo "|   |   |_______________________||       |   |    |"
echo "|   |     '----------------------'       |   |    |"
echo "|   |                            ™POMBO  |   |    |"
echo "|   |____________________________________|   |    |"
echo "|   |____________________________°_°_°___|   |    |"
echo "|                                            |    |"
echo "=================================================="

        sudo chroot $folder /bin/su - root

        echo -e "\033[1m\x1b[33m [ Unmounting dev/pts ... ]"

        sudo umount $folder/dev/pts

        echo -e " [ Unmounting /dev ... ]"

        sudo umount $folder/dev

        echo -e " [ Unmounting /proc ... ]"

        sudo umount $folder/proc

        echo -e " [ Unmounting sdcard ... ]"

        sudo umount $folder/sdcard

        echo -e " [ Unmounting /sys ... ]"

        sudo umount $folder/sys

        echo -e " \x1b[32m[ Unmounted ]\e[0m"

exit 0

    else

        termux-x11 :0 &>/dev/null & pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 &>/dev/null & sleep 1 & sleep 1

        proot-distro login ubuntu --isolated --bind /sdcard:/sdcard --bind $PREFIX/tmp/:/tmp/

    fi

elif [ $opcao = 2 ]
then

clear

echo "______________________________________________"
echo "|                                            |\ "
echo "|   _____________________________________    | \ "
echo "|   |   _______________|________   |  - ×|   |  \ "
echo "|   |   |•___________________- ×|  |     |   |   \ "
echo "|   |   |                       |  |     |   |    |"
echo "|   |   | REMOVENDO ACCLAN.. ;-;   |  |     |   |    |"
echo "|   |   |                       |__|     |   |\   |"
echo "|   |   |                       ||       |   | \  |"
echo "|   |   |                       ||       |   |  \ |"
echo "|   |   |                       ||       |   |   \|"
echo "|   |   |_______________________||       |   |    |"
echo "|   |     '----------------------'       |   |    |"
echo "|   |                            ™POMBO  |   |    |"
echo "|   |____________________________________|   |    |"
echo "|   |____________________________°_°_°___|   |    |"
echo "|                                            |    |"
echo "=================================================="

if [ -d ~/ACCLAN ]
    then
        sudo rm -rf ~/ACCLAN
        rm $PREFIX/bin/ACCLAN
    else
        proot-distro remove ubuntu &>/dev/null
        rm $PREFIX/bin/ACCLAN
fi

elif [ $opcao = 3 ]
then

clear

echo "______________________________________________"
echo "|                                            |\ "
echo "|   _____________________________________    | \ "
echo "|   |   _______________|________   |  - ×|   |  \ "
echo "|   |   |•___________________- ×|  |     |   |   \ "
echo "|   |   |                       |  |     |   |    |"
echo "|   |   | REINSTALANDO ACCLAN   |  |     |   |    |"
echo "|   |   |                       |__|     |   |\   |"
echo "|   |   |                       ||       |   | \  |"
echo "|   |   |                       ||       |   |  \ |"
echo "|   |   |                       ||       |   |   \|"
echo "|   |   |_______________________||       |   |    |"
echo "|   |     '----------------------'       |   |    |"
echo "|   |                            ™POMBO  |   |    |"
echo "|   |____________________________________|   |    |"
echo "|   |____________________________°_°_°___|   |    |"
echo "|                                            |    |"
echo "=================================================="

fi

if [ $opcao = 0 ]
then

clear 

echo "______________________________________________"
echo "|                                            |\ "
echo "|   _____________________________________    | \ "
echo "|   |   _______________|________   |  - ×|   |  \ "
echo "|   |   |•___________________- ×|  |     |   |   \ "
echo "|   |   |                       |  |     |   |    |"
echo "|   |   | ATE MAIS...           |  |     |   |    |"
echo "|   |   |                       |__|     |   |\   |"
echo "|   |   |                       ||       |   | \  |"
echo "|   |   |                       ||       |   |  \ |"
echo "|   |   |                       ||       |   |   \|"
echo "|   |   |_______________________||       |   |    |"
echo "|   |     '----------------------'       |   |    |"
echo "|   |                            ™POMBO  |   |    |"
echo "|   |____________________________________|   |    |"
echo "|   |____________________________°_°_°___|   |    |"
echo "|                                            |    |"
echo "=================================================="

sleep 3

exit 

fi
